// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuER7U6qocQLxh9yOLsQ-umphhlA3zwHA',
    appId: '1:1000714971794:web:228b8ad23b3c663368944b',
    messagingSenderId: '1000714971794',
    projectId: 'booking-app-4ed31',
    authDomain: 'booking-app-4ed31.firebaseapp.com',
    storageBucket: 'booking-app-4ed31.firebasestorage.app',
    measurementId: 'G-VMPKNMBFGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcQbE3m_rDWEcaB9VkG2jzwnQ2IYMr-HU',
    appId: '1:1000714971794:android:9764ad4c417422c268944b',
    messagingSenderId: '1000714971794',
    projectId: 'booking-app-4ed31',
    storageBucket: 'booking-app-4ed31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpRi9nOlJQkWW-Knwyd_Y3N5XSalfUycg',
    appId: '1:1000714971794:ios:e3a2e9c8772d937268944b',
    messagingSenderId: '1000714971794',
    projectId: 'booking-app-4ed31',
    storageBucket: 'booking-app-4ed31.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpRi9nOlJQkWW-Knwyd_Y3N5XSalfUycg',
    appId: '1:1000714971794:ios:e3a2e9c8772d937268944b',
    messagingSenderId: '1000714971794',
    projectId: 'booking-app-4ed31',
    storageBucket: 'booking-app-4ed31.firebasestorage.app',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxWiTv5EvHGNJCcS44cDZ-M2vIY2qvUDw',
    appId: '1:1000714971794:web:a53f9f90559ddbb468944b',
    messagingSenderId: '1000714971794',
    projectId: 'booking-app-4ed31',
    authDomain: 'booking-app-4ed31.firebaseapp.com',
    storageBucket: 'booking-app-4ed31.firebasestorage.app',
    measurementId: 'G-CHCGE2NQM8',
  );
}
